env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  Build:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/build-app.sh
      - run: ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
    
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
  
  Docker-image:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: export GIT_COMMIT="GA-$GITHUB_SHA" && chmod -x ci/build-docker.sh && chmod -x ci/push-docker.sh
      - run: export GIT_COMMIT="GA-$GITHUB_SHA" && ci/build-docker.sh
      - run: export GIT_COMMIT="GA-$GITHUB_SHA" && ci/push-docker.sh
      